# Generated by Django 2.2 on 2019-04-19 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
