# Generated by Django 2.2 on 2019-04-24 21:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0010_orders_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='item_json',
            new_name='items_json',
        ),
    ]
