# Generated by Django 2.2 on 2019-04-25 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0011_auto_20190424_1712'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
