# Generated by Django 2.2 on 2019-04-25 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0013_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='email',
        ),
    ]
